/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.KSpeech.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#include "kspeechinterface.h"

/*
 * Implementation of interface class OrgKdeKSpeechInterface
 */

OrgKdeKSpeechInterface::OrgKdeKSpeechInterface(QDBusAbstractInterfacePrivate *p)
    : QDBusAbstractInterface(p)
{
}

OrgKdeKSpeechInterface::~OrgKdeKSpeechInterface()
{
}


#include "kspeechinterface.moc"
