######################################################################
# Automatically generated by qmake (1.07a) Tue Dec 21 21:18:47 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += xhtml2ssml.h xmlelement.h
SOURCES += main.cpp xhtml2ssml.cpp xmlelement.cpp
